// <auto-generated />
using System;
using CHECKME.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CHECKME.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260213152119_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CHECKME.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("CHECKME.Models.Meditation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Technique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meditations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AudioUrl = "",
                            Description = "Базовая техника осознанного дыхания",
                            Difficulty = "Начинающий",
                            Duration = 5,
                            Technique = "Дыхание",
                            ThumbnailUrl = "/images/breathing.jpg",
                            Title = "Дыхательная медитация",
                            VideoUrl = "/videos/breathing.mp4"
                        },
                        new
                        {
                            Id = 2,
                            AudioUrl = "",
                            Description = "Почувствуйте каждую часть тела",
                            Difficulty = "Начинающий",
                            Duration = 10,
                            Technique = "Сканирование",
                            ThumbnailUrl = "/images/body-scan.jpg",
                            Title = "Сканирование тела",
                            VideoUrl = "/videos/body-scan.mp4"
                        },
                        new
                        {
                            Id = 3,
                            AudioUrl = "",
                            Description = "Развитие сострадания к себе и другим",
                            Difficulty = "Средний",
                            Duration = 15,
                            Technique = "Любящая доброта",
                            ThumbnailUrl = "/images/loving-kindness.jpg",
                            Title = "Медитация любящей доброты",
                            VideoUrl = "/videos/loving-kindness.mp4"
                        },
                        new
                        {
                            Id = 4,
                            AudioUrl = "",
                            Description = "Создание безопасного места",
                            Difficulty = "Средний",
                            Duration = 12,
                            Technique = "Визуализация",
                            ThumbnailUrl = "/images/visualization.jpg",
                            Title = "Визуализация",
                            VideoUrl = "/videos/visualization.mp4"
                        },
                        new
                        {
                            Id = 5,
                            AudioUrl = "",
                            Description = "Снятие острой тревоги",
                            Difficulty = "Начинающий",
                            Duration = 8,
                            Technique = "Дыхание",
                            ThumbnailUrl = "/images/anxiety-relief.jpg",
                            Title = "Медитация при тревоге",
                            VideoUrl = "/videos/anxiety-relief.mp4"
                        });
                });

            modelBuilder.Entity("CHECKME.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("CHECKME.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Личность",
                            Description = "Узнайте свой тип темперамента",
                            ImageUrl = "/images/temperament.jpg",
                            Title = "Тест на темперамент"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Стресс",
                            Description = "Оцените свой текущий уровень стресса",
                            ImageUrl = "/images/stress.jpg",
                            Title = "Уровень стресса"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Тревога",
                            Description = "Определите уровень тревожности",
                            ImageUrl = "/images/anxiety.jpg",
                            Title = "Шкала тревоги Бека"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Настроение",
                            Description = "Оценка симптомов депрессии",
                            ImageUrl = "/images/depression.jpg",
                            Title = "Тест на депрессию"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Эмоции",
                            Description = "Насколько хорошо вы понимаете эмоции",
                            ImageUrl = "/images/eq.jpg",
                            Title = "Тест на эмоциональный интеллект"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Личность",
                            Description = "Оценка уровня самооценки",
                            ImageUrl = "/images/selfesteem.jpg",
                            Title = "Тест на самооценку"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Работа",
                            Description = "Оценка профессионального выгорания",
                            ImageUrl = "/images/burnout.jpg",
                            Title = "Тест на выгорание"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Тревога",
                            Description = "Ситуативная и личностная тревожность",
                            ImageUrl = "/images/spilberger.jpg",
                            Title = "Тест на тревожность Спилбергера"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Стресс",
                            Description = "Как вы справляетесь со стрессом",
                            ImageUrl = "/images/coping.jpg",
                            Title = "Тест на копинг-стратегии"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Настроение",
                            Description = "Насколько вы счастливы",
                            ImageUrl = "/images/happiness.jpg",
                            Title = "Тест на уровень счастья"
                        });
                });

            modelBuilder.Entity("CHECKME.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Interpretation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("CHECKME.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("CHECKME.Models.Answer", b =>
                {
                    b.HasOne("CHECKME.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CHECKME.Models.Question", b =>
                {
                    b.HasOne("CHECKME.Models.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("CHECKME.Models.TestResult", b =>
                {
                    b.HasOne("CHECKME.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("CHECKME.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("CHECKME.Models.Test", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
